feat: Support specifying a fixed clusterIP
zitadel/zitadel-charts pull request #119
Opened 2023-08-16 17:53 UTC by meyfa

In some circumstances, it may be desired to give Zitadel a static
IP address instead of letting Kubernetes assign a random one. To
achieve this, the `clusterIP` field of a service with type `ClusterIP`
must be set to the desired IP address. This patch adds support for
specifying the `clusterIP` field in the `values.yaml` file of the
Zitadel chart.

### Definition of Ready

- [X] I am happy with the code
- [X] Short description of the feature/issue is added in the pr description
- [ ] PR is linked to the corresponding user story
- [ ] Acceptance criteria are met
- [ ] All open todos and follow ups are defined in a new ticket and justified
- [ ] Deviations from the acceptance criteria and design are agreed with the PO and documented.
- [X] No debug or dead code
- [X] My code has no repetitions
- [X] Documentation/examples are up-to-date
- [X] All non-functional requirements are met
- [ ] If possible, [the test configuration](https://github.com/zitadel/zitadel-charts/blob/main/charts/zitadel/test/installation/config_test.go) is adjusted so acceptance tests cover my changes

2023-08-16 21:59 UTC, eliobischof approved these changes

2023-08-16 22:16 UTC, eliobischof commented
Thanks for another contibution @meyfa, LGTM :pray: 

[Can you please bump the version](https://github.com/meyfa/zitadel-charts/pull/1)? I don't have the rights to push directly to your forks branch.

2023-08-16 22:16 UTC, eliobischof requested changes
Thanks for another contibution @meyfa, LGTM 🙏

https://github.com/meyfa/zitadel-charts/pull/1? I don't have the rights to push directly to your forks branch.

2023-08-16 22:19 UTC, meyfa commented
@eliobischof Sure! Done. "Allow edits by maintainers" is now checked as well, in case something else comes up.

2023-08-16 22:39 UTC, eliobischof approved these changes

2023-09-12 14:08 UTC, eliobischof approved these changes

2023-09-12 14:15 UTC, merged