feat: update appVersion to v2.54.2
zitadel/zitadel-charts pull request #210
Opened 2024-06-05 12:26 UTC by kleberbaum

### Definition of Ready

- [x] I am happy with the code
- [x] Short description of the feature/issue is added in the pr description
- [ ] PR is linked to the corresponding user story
- [x] Acceptance criteria are met
- [x] All open todos and follow ups are defined in a new ticket and justified
- [ ] Deviations from the acceptance criteria and design are agreed with the PO and documented.
- [x] No debug or dead code
- [x] My code has no repetitions
- [x] Documentation/examples are up-to-date
- [x] All non-functional requirements are met
- [ ] If possible, [the test configuration](https://github.com/zitadel/zitadel-charts/blob/main/charts/zitadel/test/installation/config_test.go) is adjusted so acceptance tests cover my changes

**What is the current behavior?**
The previously implemented workflow functionality from PR zitadel/zitadel#4544, which automatically triggered a webhook post-ZITADEL release, has been removed. Consequently, the bump workflow (introduced in zitadel/zitadel-charts#43 and discussed in Issue #105) is no longer dispatched, as it depends on this mechanism. This issue is also tracked in the Product Management Backlog under item [30889015](https://github.com/orgs/zitadel/projects/2/views/1?filterQuery=Update+the+Chart+always+to+the+latest+stable&pane=issue&itemId=30889015).

**What is the new behavior?**
This PR updates the ZITADEL version to v2.54.1 manually.

> **What could be a permanent solution?** To resolve Issue #105 it may be necessary to reimplement the changes from PR [zitadel/zitadel#4544](https://github.com/zitadel/zitadel/pull/4544) in [Current ZITADEL Release Workflow](https://github.com/zitadel/zitadel/blob/6a1ec149d307881a07866008e6b9141f1518fac0/.github/workflows/release.yml).
> 
> ```yaml
>       - uses: tibdex/github-app-token@v1
>         id: generate-token
>         with:
>           app_id: ${{ secrets.APP_ID }}
>           private_key: ${{ secrets.APP_PRIVATE_KEY }}
>       - name: Bump Chart Version
>         uses: peter-evans/repository-dispatch@v2
>         if: steps.semantic.outputs.new_release_published == 'true' && github.ref == 'refs/heads/main'
>         with:
>           token: ${{ steps.generate-token.outputs.token }}
>           repository: zitadel/zitadel-charts
>           event-type: zitadel-released
>           client-payload: '{"semanticoutputs": "${{ steps.semantic.outputs }}"}'
> ```
> 
> However, the current bump workflow does not appear to be functional, as indicated by [![Bump Version](https://github.com/zitadel/zitadel-charts/actions/workflows/bump.yml/badge.svg)](https://github.com/zitadel/zitadel-charts/actions/workflows/bump.yml).
> 
> ![image](https://private-user-images.githubusercontent.com/26285351/326801112-0ee8a55c-ac11-4457-9f97-33aa1c1b3d47.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc1OTAxNzYsIm5iZiI6MTcxNzU4OTg3NiwicGF0aCI6Ii8yNjI4NTM1MS8zMjY4MDExMTItMGVlOGE1NWMtYWMxMS00NDU3LTlmOTctMzNhYTFjMWIzZDQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA1VDEyMTc1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFiODJhMjNlZTBjZjE4NWFkYTI5NWNiZmFlNDI3MzRmOWVkN2RjYjdhNGJlMGQ0NzlhZWMxOTE4N2QyZTEwNmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pocg8ZEMgsl-g5MdJJuqYC3mJLgatoQk_ek5vxPI9yE)
> 
_Originally posted by @kleberbaum in https://github.com/zitadel/zitadel-charts/issues/198

**Your feedback and suggestions would be greatly appreciated.**

2024-06-13 09:48 UTC, eliobischof requested changes

2024-06-13 09:48 UTC, eliobischof commented on charts/zitadel/Chart.yaml
> +appVersion: "v2.54.1"
We had a bug in v2.54.1 that probably also explains that the tests fail. 

```suggestion
appVersion: "v2.54.2"
```

2024-06-16 15:42 UTC, panapol-p commented
hi, @kleberbaum  @eliobischof  I think we should update the CockroachDB chart version in the example and add more information about how to migrate to this chart.

FYI: Zitadel >= v2.53.0 cannot run on CockroachDB chart v11.2.1 (v23.1.1) It requires an upgrade to at least CockroachDB v23.2
Reference: [Zitadel Documentation](https://zitadel.com/docs/support/advisory/a10009#description)

As an example, for CockroachDB, we currently use chart v11.2.1 (CockroachDB v23.1.11). It would be better to upgrade to the latest version, helm chart v13.0.0 (CockroachDB v24.1.0). However, the database cannot be upgraded directly. You need to first upgrade from chart v11.2.1 (v23.1.1) to chart v12.0.5 (v23.2.5) and then to v13.0.0 (v24.1.0)

https://github.com/zitadel/zitadel-charts/blob/ff1465cc6921717cd29cc6e4cf8a9e19a5774c56/examples/4-cockroach-secure/README.md?plain=1#L12

2024-06-19 05:12 UTC, kleberbaum commented
> hi, @kleberbaum @eliobischof I think we should update the CockroachDB chart version in the example and add more information about how to migrate to this chart.

_Originally posted by @panapol-p in https://github.com/zitadel/zitadel-charts/issues/210#issuecomment-2171748085_

I've updated the CockroachDB Chart version to [v13.0.1](https://github.com/zitadel/zitadel-charts/pull/210/commits/f86e4705b16ecde4503dca6c6547ae1f326d19f2), but the checks are still failing.

I think we should upgrade the [ZITADEL chart version to 8.0.0](https://github.com/zitadel/zitadel-charts/pull/210/commits/6bc6d9238e39c25d4c9edeb82e783919f0313b66) as this will be a breaking change. A migration guide is also necessary.

2024-06-22 21:07 UTC, Mohit21GoJs commented
Hi @kleberbaum We would like to use the version 2.54.2 or 2.55.0 in our apps, is there any timeline or examples to use it in our self hosted k8s environment?

2024-06-23 05:12 UTC, panapol-p commented
Hi, @Mohit21GoJs

To manually upgrade Zitadel to a new version:

1. **Backup Your Database:** Ensure you have a backup of your database before starting the upgrade process.

2. **Upgrade CockroachDB:**
   If you are using CockroachDB version <= v23.1.1, you must upgrade the database first. Run the following command:
   ```
   helm upgrade db cockroachdb/cockroachdb --version 12.0.5 --reuse-values
   ```
   Note: You can check the database upgrade progress by using this command:
   ```
   kubectl get pods \
   -o jsonpath='{range .items[*]}{.metadata.name}{"\t"}{.spec.containers[0].image}{"\n"}'
   ```

3. **Update Zitadel Configuration:**
   Add the image tag in your Zitadel configuration (`zitadel-values.yaml`):
   ```
   image:
     tag: v2.54.3
   ```

4. **Upgrade Zitadel:**
   Run the following command to upgrade Zitadel:
   ```
   helm upgrade my-zitadel zitadel/zitadel --values zitadel-values.yaml
   ```

If you use namespaces for your database and Zitadel, remember to include the `--namespace` flag for each command.

2024-06-28 04:47 UTC, panapol-p commented
@kleberbaum could you pls update this branch for new error handling

2024-06-28 04:56 UTC, eliobischof commented
@kleberbaum I am not allowed to commit to this PR, so I created a new one https://github.com/zitadel/zitadel-charts/pull/219 and hope you have no hard feelings 🥲

I close this, for now. I see you should already have a ZITADEL shirt :+1: :pray:

2024-06-28 04:56 UTC, closed without merging