chore: propose to use stable as default image
zitadel/zitadel-charts pull request #30
Opened 2022-08-08 15:47 UTC by fforootd

2022-08-10 09:50 UTC, eliobischof commented
I couldn't find any best practices for this.
The best thing IMO would be if we published additional docker tags for only major and minor versions, then set v2 as appVersion?

2022-08-10 09:55 UTC, eliobischof requested changes

2022-08-10 09:55 UTC, eliobischof commented on charts/zitadel/Chart.yaml
>  appVersion: "v2.0.0-amd64"
```suggestion
appVersion: "stable"
```

2022-08-10 09:55 UTC, eliobischof commented on charts/zitadel/values.yaml
> +  tag: "stable"
```suggestion
  tag: ""
```

2022-08-10 16:32 UTC, fforootd reviewed
Incorporated the changes

2022-08-11 09:01 UTC, eliobischof commented
Grafana, Cockroach and GitLab increment their chart versions when the app versions increment:
- https://github.com/grafana/helm-charts/pull/1633
- https://github.com/cockroachdb/helm-charts/pull/259
- https://gitlab.com/gitlab-org/charts/gitlab/-/merge_requests/2712

2022-08-11 09:04 UTC, eliobischof commented
If we want have a fixed appVersion for a chart version, maybe we should automate things.

2022-08-11 09:16 UTC, eliobischof commented
I think we should publish a stable channel for the chart repository as a whole somehow

2022-08-12 07:57 UTC, fforootd commented
> I think we should publish a stable channel for the chart repository as a whole somehow

And when do we want to do this? In this PR, or should we proceed first with merging?

2022-08-31 07:38 UTC, eliobischof commented
> > I think we should publish a stable channel for the chart repository as a whole somehow
> 
> And when do we want to do this? In this PR, or should we proceed first with merging?

I think we should close this PR, implement https://github.com/zitadel/zitadel/issues/4219 instead and create a new issue for the charts stable channel

2022-09-12 21:44 UTC, juliusrickert commented
Using mutable image tags is considered to be an anti–pattern.

Firstly, you'd need to use a `pullPolicy` of `Always`, breaking in case of registry downtime or other issues.
Secondly, in case of a rollback, the image has been overwritten, so the rolled-back release may not work, or, potentially worse, different nodes could have different versions of the image.

Same goes for a Helm chart and an app version. Otherwise, it may be impossible to install an old version of the chart due to configuration changes or similar.

Automating the release process may be the way to go here. If the main application strongly adheres to semver, I think this should work.

2022-09-12 21:53 UTC, fforootd commented
> Using mutable image tags is considered to be an anti–pattern.
> 
> Firstly, you'd need to use a `pullPolicy` of `Always`, breaking in case of registry downtime or other issues. Secondly, in case of a rollback, the image has been overwritten, so the rolled-back release may not work, or, potentially worse, different nodes could have different versions of the image.
> 
> Same goes for a Helm chart and an app version. Otherwise, it may be impossible to install an old version of the chart due to configuration changes or similar.
> 
> Automating the release process may be the way to go here. If the main application strongly adheres to semver, I think this should work.

True, I agree with this. Although I think using a `latest` tag is fine for easy to start cases.

Since ZITADEL strictly uses semver it should be feasible to create new tags as needed for this helm chart.

Since @eliobischof is in vacation this week he will pick-up next week with this :grin:

2022-10-12 21:47 UTC, fforootd commented
@eliobischof can you have a look into this?

2022-10-12 22:19 UTC, eliobischof commented
I still think it is a bad idea to use mutable tags by default because I don't assume the chart is just used in easy to start cases.

I would rather add a `--set image.tag=latest` option to the docs and automatically trigger chart releases when ZITADEL is released, regardless of the ZITADEL tags release channel. I can do it tomorrow, it's not a big deal.

2022-10-12 22:28 UTC, fforootd commented
> I still think it is a bad idea to use mutable tags by default because I don't assume the chart is just used in easy to start cases.

I do to, what I meant by looking into, is that we should automate the lifecycle of the helm chart depending on the ZITADEL release.

2022-10-13 09:23 UTC, eliobischof commented
Replaced by #43

2022-10-13 09:23 UTC, closed without merging